import { TProduct } from '~@/shared/ui/product-card/product-card.types';

export const PVS_DATA = [
	{
		title: 'Удлинители в бухте',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> без заземления, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: false,
		isProfessional: false,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 101,
						plugs: '2х1,0',
						length: '10 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 102,
						plugs: '2х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 103,
						plugs: '2х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 104,
						plugs: '2х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 105,
						plugs: '2х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 106,
						plugs: '2х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 107,
						plugs: '2х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 108,
						plugs: '2х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 109,
						plugs: '2х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 110,
						plugs: '2х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 111,
						plugs: '2х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 112,
						plugs: '2х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 113,
						plugs: '2х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 114,
						plugs: '2х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 115,
						plugs: '2х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители в бухте ',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		category: 1,
		socket: 'крышка в розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 116,
						plugs: '3х1,0',
						length: '10 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 117,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 118,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 119,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 120,
						plugs: '3х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 121,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 122,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 123,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 124,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 125,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 126,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 127,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 128,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 129,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 130,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на раме ',
		description: `Удлинители с изолированным кабелем медным на рамке для его намотки, <br/> без заземления, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: false,
		isProfessional: false,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 201,
						plugs: '2х1,0',
						length: '10 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 202,
						plugs: '2х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 203,
						plugs: '2х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 204,
						plugs: '2х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 205,
						plugs: '2х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 206,
						plugs: '2х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 207,
						plugs: '2х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 208,
						plugs: '2х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 209,
						plugs: '2х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 210,
						plugs: '2х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 211,
						plugs: '2х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 212,
						plugs: '2х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 213,
						plugs: '2х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 214,
						plugs: '2х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 215,
						plugs: '2х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на рамке ',
		description: `Удлинители с изолированным кабелем медным на рамке для его намотки, <br/> с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		category: 1,
		socket: 'крышка в розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 116,
						plugs: '3х1,0',
						length: '10 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 117,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 118,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 119,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 120,
						plugs: '2х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 121,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 122,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 123,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 124,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 125,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 126,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 127,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 128,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 129,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 130,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на садовой пластиковой катушке и удобным местом наматывания, <br/> без заземления, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: false,
		isProfessional: true,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 301,
						plugs: '2х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 302,
						plugs: '2х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 303,
						plugs: '2х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 304,
						plugs: '2х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 305,
						plugs: '2х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 306,
						plugs: '2х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 307,
						plugs: '2х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 308,
						plugs: '2х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 309,
						plugs: '2х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 310,
						plugs: '2х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 311,
						plugs: '2х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
					{
						article: 312,
						plugs: '2х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: false,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на садовой пластиковой катушке и удобным местом наматывания, <br/> без заземления, со степенью защиты «IP44» (каучуковая розетка и крышка), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: true,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 313,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 314,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 315,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 316,
						plugs: '3х1,0',
						length: '50 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 317,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 318,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 319,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 320,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 321,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 322,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 323,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 324,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},

	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на садовой пластиковой катушке и удобным местом наматывания, <br/> без заземления, со степенью стандартной защиты «IP20» (не менее 12.5 мм), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: false,
		isProfessional: true,
		category: 1,
		socket: 'твердая защита',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 401,
						plugs: '2х1,0',
						length: '20 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 402,
						plugs: '2х1,0',
						length: '30 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 403,
						plugs: '2х1,0',
						length: '40 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 404,
						plugs: '2х1,0',
						length: '50 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 405,
						plugs: '2х1,5',
						length: '20 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 406,
						plugs: '2х1,5',
						length: '30 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 407,
						plugs: '2х1,5',
						length: '40 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 408,
						plugs: '2х1,5',
						length: '50 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 409,
						plugs: '2х2,5',
						length: '20 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 410,
						plugs: '2х2,5',
						length: '30 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 411,
						plugs: '2х2,5',
						length: '40 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 412,
						plugs: '2х2,5',
						length: '50 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на садовой пластиковой катушке и удобным местом наматывания, <br/> с заземлением, со степенью стандартной защиты «IP20» (не менее 12.5 мм), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: true,
		category: 1,
		socket: 'защита от мусора',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 413,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 414,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 415,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 416,
						plugs: '3х1,0',
						length: '50 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 417,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 418,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 419,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 420,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 421,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 422,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 423,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 424,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на садовой пластиковой катушке и удобным местом наматывания, <br/> с заземлением, со степенью стандартной защиты «IP20» (защита от мусора), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: false,
		isProfessional: true,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 401,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 402,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 403,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 404,
						plugs: '3х1,0',
						length: '50 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 405,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 406,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 407,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 408,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 409,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 410,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 411,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
					{
						article: 412,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: false,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители на катушке',
		description: `Удлинители с кабелем медным (проводом) и виниловым изолированием, <br/> на металлической катушке с держателями и удобным местом наматывания, <br/> с заземлением, со степенью защиты «IP44» (защита от влаги и пыли), <br/> с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: true,
		category: 1,
		socket: 'крышка на розетке',
		variants: [
			{
				variant: 2200,
				options: [
					{
						article: 413,
						plugs: '3х1,0',
						length: '20 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 414,
						plugs: '3х1,0',
						length: '30 м',
						security: 'IP44',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 415,
						plugs: '3х1,0',
						length: '40 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 416,
						plugs: '3х1,0',
						length: '50 м',
						security: 'IP20',
						power: '2200 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 3500,
				options: [
					{
						article: 417,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 418,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 419,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 420,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP20',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 421,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 422,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 423,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 424,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP20',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
];

export const KG_DATA = [
	{
		title: 'Удлинители силовые в бухте',
		description: `Удлинители силовые с кабелем гибким и холодостойким, в бухте,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: false,
		settings: {
			isEco: true,
			isGost: false,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 501,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 502,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 503,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 504,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 505,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 506,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 507,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 508,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 509,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 510,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на колодке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, на колодке,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: false,
		options: {
			isEco: true,
			isGost: false,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 511,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 512,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 513,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 514,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 515,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 516,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 517,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 518,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 519,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 520,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на колодке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, по «ЭКО»,
    <br/>
    на пластиковой рамке и удобным местом и функционалом намотки,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: true,
		options: {
			isEco: true,
			isGost: false,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 531,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 532,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 533,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 534,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на катушке',
		fulltitle: 'Удлинители силовые на пластиковой катушке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, по «ЭКО»,
    <br/>
    на пластиковой катушке с держателями и удобным местом наматывания,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: true,
		isPlastic: true,
		isMetalic: false,
		options: {
			isEco: true,
			isGost: false,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 535,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 536,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 537,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 538,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 539,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 540,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 541,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 542,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на катушке',
		fulltitle: 'Удлинители силовые на металлической катушке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, по «ЭКО»,
    <br/>
    на металлической катушке с держателями и удобным местом наматывания,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: true,
		isPlastic: false,
		isMetalic: true,
		isCatushka: true,
		options: {
			isEco: true,
			isGost: false,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 535,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 536,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 537,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 538,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 539,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 540,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 541,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 542,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на колодке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, в бухте,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: false,
		options: {
			isEco: false,
			isGost: true,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 601,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 602,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 603,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 604,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 605,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 606,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 607,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 608,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 609,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
					{
						article: 610,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '1 розетка',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на колодке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, на колодке,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: false,
		options: {
			isEco: false,
			isGost: true,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 611,
						plugs: '3х1,5',
						length: '10 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 612,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 613,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 614,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 615,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '3 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 616,
						plugs: '3х2,5',
						length: '10 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 617,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 618,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 619,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
					{
						article: 620,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '3 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на катушке',
		fulltitle: 'Удлинители силовые на пластиковой катушке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, по «ГОСТ»,
    <br/>
    на пластиковой катушке с держателями и удобным местом наматывания,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: true,
		isPlastic: true,
		isMetalic: false,
		isCatushka: true,
		options: {
			isEco: false,
			isGost: true,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 635,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 636,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 637,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 638,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 639,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 640,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 641,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 642,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
	{
		title: 'Удлинители силовые на катушке',
		fulltitle: 'Удлинители силовые на металлической катушке',
		description: `Удлинители силовые с кабелем гибким и холодостойким, по «ГОСТ»,
    <br/>
    на металлической катушке с держателями и удобным местом наматывания,
    <br/>
    с заземлением, со степенью защиты «IP44» (каучуковая розетка и крышка),
    <br/>
    с европейской вилкой «16А», с поддержанием напряжения сети в «220В»`,
		grounding: true,
		isProfessional: false,
		isSpec: true,
		options: {
			isEco: false,
			isGost: true,
			temp: 'от +40°C до -60°C ',
		},
		category: 2,
		variants: [
			{
				variant: 3500,
				options: [
					{
						article: 635,
						plugs: '3х1,5',
						length: '20 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 636,
						plugs: '3х1,5',
						length: '30 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 637,
						plugs: '3х1,5',
						length: '40 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 638,
						plugs: '3х1,5',
						length: '50 м',
						security: 'IP44',
						power: '3500 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
			{
				variant: 4000,
				options: [
					{
						article: 639,
						plugs: '3х2,5',
						length: '20 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 640,
						plugs: '3х2,5',
						length: '30 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 641,
						plugs: '3х2,5',
						length: '40 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
					{
						article: 642,
						plugs: '3х2,5',
						length: '50 м',
						security: 'IP44',
						power: '4000 Вт',
						socket: '4 розетки',
						grounding: true,
					},
				],
			},
		],
	},
];
